---
title: "Transfer Learning with VGG-16 Model"
output: html_document
---


```{r}
reticulate::use_condaenv("tf-gpu", required = TRUE)
require(keras)
```

```{r Data preprocessing}
train_dir <- paste0(here::here(), "/cats_and_dogs/cats_and_dogs_small/train")
validation_dir <- paste0(here::here(), "/cats_and_dogs/cats_and_dogs_small/validation")

train_datagen <- image_data_generator(rescale = 1/255,
                                      width_shift_range=0.1,
                                      height_shift_range=0.1,
                                      horizontal_flip=TRUE )
validation_datagen <- image_data_generator(rescale = 1/255)

train_generator <- flow_images_from_directory(
  train_dir,
  train_datagen, target_size = c(224, 224),
  batch_size = 20,
  class_mode = "binary"
)

validation_generator <- flow_images_from_directory(
  validation_dir,
  validation_datagen, target_size = c(224, 224),
  batch_size = 20,
  class_mode = "binary"
)
```

```{r}
conv_base <- application_vgg16(
  weights = "imagenet",
  include_top = FALSE,
  input_shape = c(224, 224, 3)
)
```

```{r}
model <- keras_model_sequential() %>%
  conv_base %>%
  layer_flatten() %>%
  layer_dense(units = 256, activation = "relu") %>%
  layer_dropout(rate = 0.5) %>%
  layer_dense(units = 1, activation = "sigmoid")


freeze_weights(conv_base)
```

```{r}
model %>% compile(
  optimizer = optimizer_adam(lr = 2e-5),
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)
```

```{r}
history <- model %>% fit_generator(
  train_generator,
  steps_per_epoch = 100,
  epochs = 100,
  validation_data = validation_generator,
  validation_steps = 50
)
```

```{r}
model %>% save_model_hdf5("classif_transferlearning_vgg.h5")
```

